### ISSUE TITLE
Specify application features

### ISSUE THREAD

**Issue by OrkenWhite** [SnapTrash/SnapTrash-docs#5]
We need to explicitly specify the features we aim to implement during the course.

**Comment by GioGue** [comment]
Meeting 18.03:

- @hanyghorbel Would write the app specification till 20.03

**Comment by OrkenWhite** [comment]
There were some delays, but we have to be ready by 27.03

**Comment by OrkenWhite** [comment]
functionality_doc branch contains the document for this

**Comment by OrkenWhite** [comment]
Done with pull request #17
